

#set it true or false so players cant break blocks
killstreak:
 5message: '&2 %killer% &7has just reached to 5 KILLSTREAKS'
 10message: '&7Be Careful! Player &2 %killer% has reached to &c10 killstreaks!'
 15message: '&7PLAYER &l&4%killer% &7IS &l&4INSANE &7HE REACHED TO &c15 KILLSTREAKS'
 lastmessage: '&4%killer% This guy is &4&lGOD he added another kill to his collection'
no-item-drop: true
block-break: true
scoreboard:
 title: '&3Knockback&bFFA'
 lines:
  - '&7Hi &3%player_name%!'
  - '&f Welcome to &6Knockback&eFFA'
  - ''
  - '&7Players online : %server_online%'
  - ''
  - 'Hope you enjoy playing in YourServer ;)'
  - 'yourdomain.com'
  - 'play.yourdomain.com'

