# delay between arena switches in seconds (default is 900 seconds / 15 minutes)
arena-switch-timer: 900
# clears items after a specific period (default time is 60 seconds / 1 minutes)
wipe-items:
  enabled: true
  period: 60
# Bungee makes players join to the game when they join your server (You don't need save-inventory-on-join and mainlobby if this is true)
bungee: false
# stores player inventory before they join the game but you can set it to false so when a player leaves the game. They'll lose their previous inventory before they join the game(Bungee-Mode Only)
save-inventory-on-join: true
# this is configurable in sounds.yml
join-sound: true
# amount of given coins on kill
kill-prize: 10
default-void-damage: 6
# autoresetcheck-blocks is amount of blocks that will be checked in every second
# default is 10000 blocks or 10k
autoresetcheck-blocks: 10000
# trails won't work in these blocks
no-trail-blocks:
  - 'WATER'
  - 'LAVA'
  - 'SIGN'
  - 'WALLSIGN'
