name: KnockbackFFA
version: '${project.version}'
main: me.gameisntover.kbffa.KnockbackFFA
authors: [ GaMeIsNtOvEr , iiAhmedYT]
api-version: 1.13
description: Knockback ffa is a gamemode which gives every players knockback stick and some other stuffs which makes the game more fun!

