name: KnockbackFFA
version: '${project.version}'
main: me.gameisntover.kbffa.knockbackffa.KnockbackFFA
api-version: 1.16
authors: [ GaMeIsNtOvEr ]
description: Knockback ffa is a gamemode which gives every players knockback stick and some other stuffs which makes the game more fun!
commands:
  setspawn:
    description: sets the spawnpoint so players can spawn there!
    permission: kbffa.command.setspawn
    permission-message: Sorry but you need to have permission for this!
  reload:
    description: reload the config
    permission: kbffa.command.reload
    permission-message: Sorry but you need to have permission for this!

  wand:
    description: Gives player safezone wand selector
    permission: kbffa.command.wand
    permission-message: Sorry but you need to have permission for this!

  setsafezone:
    description: Sets the safezone
    permission: kbffa.command.setsafezone
    permission-message: Sorry but you need to have permission for this!
