name: KnockbackFFA
version: '${project.version}'
main: me.gameisntover.kbffa.knockbackffa.KnockbackFFA
api-version: 1.16
authors: [ GaMeIsNtOvEr ]
description: Knockback ffa is a gamemode which gives every players knockback stick and some other stuffs which makes the game more fun!
commands:
  setspawn:
    description: sets the spawnpoint so players can spawn there!
    permission: kbffa.command.setspawn
    permission-message: Sorry but you need to have permission for this!
  reload:
    description: reload the config
    permission: kbffa.command.reload
    permission-message: §cSorry but you need to have permission for this!

  wand:
    description: Gives player safezone wand selector
    permission: kbffa.command.wand
    permission-message: §cSorry but you need to have permission for this!

  setsafezone:
    description: Sets the safezone
    permission: kbffa.command.setsafezone
    permission-message: §cSorry but you need to have permission for this!
  gotoworld:
    description: Teleports player to world
    permission: kbffa.command.gotoworld
    permission-message: §cSorry but you need to have permission for this!
  leave:
    description: Teleports player to mainlobby if bungeemode is false
    permission: kbffa.command.leave
    permission-message: §cSorry but you need to have permission for this!
  setMainLobby:
    description: Sets the mainlobby spawn (works only in bungeemode false)
    permission: kbffa.command.setmainlobby
    permission-message: §cSorry but you need to have permission for this!
  join:
    aliases: joingame
    description: Teleports player to mainlobby if bungeemode is false
    permission: kbffa.command.join
    permission-message: §cSorry but you need to have permission for this!
  createworld:
    description: Creates a new world
    permission: kbffa.command.createworld
    permission-message: §cSorry but you need to have permission for this!
  createarena:
    description: Creates a new arena
    permission: kbffa.command.createarena
    permission-message: §cSorry but you need to have permission for this!
  editarena:
    description: Edits an arena
    permission: kbffa.command.editarena
    permission-message: §cSorry but you need to have permission for this!