name: KnockbackFFA
version: '${project.version}'
main: me.gameisntover.kbffa.knockbackffa.KnockbackFFA
api-version: 1.16
authors: [ GaMeIsNtOvEr ]
description: Knockback ffa is a gamemode which gives every players knockback stick and some other stuffs which makes the game more fun!

commands:
  kits:
    description: GUI Kits
    permission: kbffa.command.kits
    permission-message: Sorry but you need to have permission for this!
  setspawn:
    description: sets the spawnpoint so players can spawn there!
    permission: kbffa.command.setspawn
    permission-message: Sorry but you need to have permission for this!
    usage: just stay on the position that you wanna set the spawn then type /setspawn if you done this. don't worry this message is just a reminder
  reload:
    description: reload the config
    permission: kbffa.command.reload
    permission-message: Sorry but you need to have permission for this!
