name: KnockbackFFA
version: '${project.version}'
main: me.gameisntover.kbffa.knockbackffa.KnockbackFFA
authors: [ GaMeIsNtOvEr ]
api-version: 1.13
softdepend:
  - 'PlaceholderAPI'
description: Knockback ffa is a gamemode which gives every players knockback stick and some other stuffs which makes the game more fun!
commands:
  createkit:
    permission: 'kbffa.command.createkit'
    description: 'Create a kit'
    permission-message: §cSorry but you need to have permission for this!
  delkit:
    permission: 'kbffa.command.delkit'
    description: 'Delete a kit'
    permission-message: §cSorry but you need to have permission for this!
  reload:
    description: reload the config
    permission: kbffa.command.reload
    permission-message: §cSorry but you need to have permission for this!
  wand:
    description: Gives player positionselector wand
    permission: kbffa.command.wand
    permission-message: §cSorry but you need to have permission for this!
  setvoid:
    description: Sets the void to the current position
    permission: kbffa.command.setvoid
    permission-message: §cSorry but you need to have permission for this!
  setsafezone:
    description: Sets the safezone
    permission: kbffa.command.setsafezone
    permission-message: §cSorry but you need to have permission for this!
  gotoworld:
    description: Teleports player to world
    permission: kbffa.command.gotoworld
    permission-message: §cSorry but you need to have permission for this!
  leave:
    description: Teleports player to mainlobby if bungeemode is false
    permission: kbffa.command.leave
    permission-message: §cSorry but you need to have permission for this!
  setmainlobby:
    description: Sets the mainlobby spawn (works only in bungeemode false)
    permission: kbffa.command.setmainlobby
    permission-message: §cSorry but you need to have permission for this!
  join:
    aliases: joingame
    description: Teleports player to mainlobby if bungeemode is false
    permission: kbffa.command.join
    permission-message: §cSorry but you need to have permission for this!
  createworld:
    description: Creates a new world
    permission: kbffa.command.createworld
    permission-message: §cSorry but you need to have permission for this!
  createarena:
    description: Creates a new arena
    permission: kbffa.command.createarena
    permission-message: §cSorry but you need to have permission for this!
  editarena:
    description: Edits an arena
    permission: kbffa.command.editarena
    permission-message: §cSorry but you need to have permission for this!
  specialitems:
    description: GUI with special items for kit creation
    permission: kbffa.command.specialitems
    permission-message: §cSorry but you need to have permission for this!
permissions:
  kbffa.command.specialitems:
    default: op
  kbffa.command.createkit:
    default: op
  kbffa.command.delkit:
    default: op
  kbffa.command.reload:
    default: op
  kbffa.command.wand:
    default: op
  kbffa.command.setvoid:
    default: op
  kbffa.command.setsafezone:
    default: op
  kbffa.command.gotoworld:
    default: op
  kbffa.command.leave:
    default: not op
  kbffa.command.join:
    default: not op
  kbffa.command.createworld:
    default: op
  kbffa.command.createarena:
    default: op
  kbffa.command.editarena:
    default: op
  kbffa.command.setmainlobby:
    default: op
